# fly.toml app configuration file generated for pomabot on 2026-01-08T08:30:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pomabot'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  API_PORT = '4000'
  MAX_MARKETS = '300'
  MAX_SIGNAL_HISTORY = '15'
  MIN_LIQUIDITY = '15000'
  NODE_ENV = 'production'
  POLL_INTERVAL = '60000'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 200
    soft_limit = 100

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
